### ISSUE TITLE
not able to run aggregator-cli.cmd file

### ISSUE THREAD

**Issue by prashanthbv12** [tfsaggregator/aggregator-cli#107]
I downloaded the latest version and built using VS 2019 with .net core 3.1 installed. 
I am getting below error while running  aggregator-cli.cmd. Pleas help

I have installed 2.1 runtime as well but still facing same issue.

C:\tools\aggregator-cli\aggregator-cli-master\src\aggregator-cli\bin\Debug\netcoreapp3.1>aggregator-cli.cmd (My run command)

Another version of .Net Core Runtime is installed, please install version 2.1 from https://dotnet.microsoft.com/download

**Comment by dmbaio** [comment]
On the 0.9.8 release I found that I had to uninstall all versions higher than 2.1 before it would run.

**Comment by prashanthbv12** [comment]
@dmbaio Thank you. It is fine now

**Comment by dmbaio** [comment]
Out of curiosity, is that version causing service hooks to trigger twice? When my rules execute and make changes, those changes seem to trigger the service hook to run the rule again. I downloaded the source code and also incorporated some changes that have been done since the most recent release, so I'm trying to figure out if it used to happen on that release too or just since then.
