### ISSUE TITLE
Save Failed VS403351: Test Operation for path /rev failed value 68 not equal to 67

### ISSUE THREAD

**Issue by ericbehughes** [tfsaggregator/aggregator-cli#128]
# Steps to reproduce

> create sample instance running 0.9.10 runtime
> use same rule attached below
> open log stream in azure portal

# rule file

```csharp
logger.WriteInfo("BEGIN closeeverythingonupdate function");
var currentWorkItem = self;

var workitems = self.Children;

const string StateNew = "New";
const string StateActive = "Active";
const string StateClosed = "Closed";

var originalState = self.State;
var newState = self.State;

logger.WriteInfo(workitems.Count().ToString());
workitems = workitems.Where(o => o.Id != self.Id);
if (workitems.All(c => c.State.Equals(StateClosed)))
{
 logger.WriteInfo("everything closed");
 newState = StateClosed;
}
 
else if (workitems.Any(c => !c.State.Equals(StateClosed) && !c.State.Equals(StateNew)))
  newState = StateActive;
else
  newState = StateNew;

if (newState.Equals(originalState))
  return;

self.State = newState;

return "END closeeverythingonupdate function";
```

## Expected behavior
>Logs should not be backwards (read from bottom up)
>Random internal test error messages should not be visible
## Actual behavior
See picture below 
![aggregator](https://user-images.githubusercontent.com/9938665/83310474-28f04980-a1da-11ea-9740-33b1fcd049b1.PNG)
## Environment

> Windows 10 Enterprise
> Version 10.0.18362

**Comment by ericbehughes** [comment]
@denious

**Comment by giuliov** [comment]
How messages appear in Azure Portal is not under our control, so much that we create and send the logs to an App Insight for production use.

The error message is from Azure DevOps: the way you changed the work item breaks some rule and is rejected. I suggest to analyse the reason and tweak the rule accordingly.

**Comment by denious** [comment]
@giuliov Sucks about the logs as it means no streaming.

As for the error message, how would we find out what "rule" is broken? The code is super simple: all it does is update the item state, and as far as I'm aware there are no custom "rules" in our DevOps setup.

For example, what does path "/rev" mean, and what are test values 67 and 68?

**Comment by BobSilent** [comment]
The "error" looks like #125

Can you please check https://github.com/tfsaggregator/aggregator-cli/issues/125#issuecomment-623066356

**Comment by denious** [comment]
Definitely related. All we want to do is update the parent state depending on the changes to the children (Close, New, Active, etc.), so regardless of the conflict the update should go through. Is there a workaround to ignore such conflicts?

**Comment by BobSilent** [comment]
Can you please check
```
Can you check the history of the work item if there was another change.
And what change it was, is it another rule running?
```

Currently no workaround, as I wrote I also struggle with this behavior.

But your rule should get triggered for every revision update. So for the new revision you also should get a trigger.
The situation where I have an issue with it is a little bit different, when I have a rule exit criteria defined (at the beginning) which relies on some changed values `selfUpdate` (not current values `self`).
If the rule would like to update the Workitem and it is not possible due to this Revision conflict, my rule gets triggered once again for the new revision but if now the changes values are different the rule would not update the Workitem anymore. This leads to incomplete updates.


So I would like to change the behavior, I am just thinking about two possible solutions
1. Breaking with old behavior: simply get rid of this check to ensure the revision triggered the rule is still the latest Workitem revision
2. Non breaking: add a configuration possibility e.g. per rule to disable the behavior. Which needs the understanding when this makes sense to do the configuration.

Writing the lines there is a possible third option, or more or less 2'. A combination of 1 and 2
3. Breaking with old behavior: change default behaviour to always update the Workitem and do not check revision. And add a configuration possibility to enable the check

Any opinions?

**Comment by giuliov** [comment]
@denious streaming works in a simple scenario, so that I use for automated integration testing. Frankly, I never saw messages in wrong order, but duplicates are the norm.

@BobSilent I am more for # 2, an explicit opt-in. Checks are there for a reason. I think we should document better what happens so people is more aware of what happens, which is non-trivial, and the options they have

**Comment by denious** [comment]
@BobSilent We went with the option of limiting triggers and told our developers to never touch the state for now. Works fine!

![image](https://user-images.githubusercontent.com/7120854/83480320-98776a80-a460-11ea-9538-7c8806f84f5a.png)

But yes, option #2 would be great. Configuration is always good.

**Comment by giuliov** [comment]
@ericbehughes , have you tried the [check revision](https://tfsaggregator.github.io/docs/v3/rules/#check-revision-directive) directive in the new versions?

**Comment by denious** [comment]
@giuliov Ever since limiting the trigger events this hasn't been an issue for us (Eric and I work together) so we haven't tried any other approach.
