### ISSUE TITLE
On Update Events, is it possible to update a work item as the previous committer rather than the service hook owner?

### ISSUE THREAD

**Issue by DanHibbert** [tfsaggregator/aggregator-cli#62]
In my example, when a rule for created/updated is activated, it make a change to a field in the current work item.  This shows up in the history graph as expected but as executed by the Service Hook Owner.  

Is it possible to set the Changed By for the rule to the person who saved the Work Item ?

Thanks
Dan

**Comment by giuliov** [comment]
Need time to look into this. I should be able to get back in a day or two.

**Comment by DanHibbert** [comment]
Thank you for looking into it 👍

**Comment by BobSilent** [comment]
@giuliov I think this is a hint https://stackoverflow.com/a/53964648

1. a PAT with appropriate permission to "Bypass rules on work item updates" is needed
2. ChangedBy needs to be updated to the (on behalf) account
3. RuleEng Code change to bypassRules:true on Update/Save work item

I also would like to have this, but one have to find a good way to configure it. otherwise it could be breaking
1. Configure per Rule to make changes on behalf. In RuleEng Code the ChangedBy can be set together with bypassRules:true
2. Let the rule author decide to set self.ChangedBy in rule code, then RuleEng Code needs to handle this and set the bypassRules:true if workitem.ChangedBy was changed

For all scenarios a PAT needs to be provided with appropriate permissions.

**Comment by giuliov** [comment]
Included in [v0.9.8](https://github.com/tfsaggregator/aggregator-cli/releases/tag/v0.9.8).
