### ISSUE TITLE
How to get values of Successor and Predecessor task's fields...

### ISSUE THREAD

**Issue by KamranAslamBhatti** [tfsaggregator/aggregator-cli#75]
Hi,
How do I get successor and predecessor field values? Following is an example which I used to get Parent and Child tasks field values, but when I use Successor or Predecessor then it gives error.

var parent = self.Parent;
var child = self.Children;
child["Microsoft.VSTS.Scheduling.TargetDate"] =self["Microsoft.VSTS.Scheduling.TargetDate"];

As in above code assigning value of parent field to child field, how can I do the same for successor and predecessor task fields.
var successor = self.Successor; ---> This gives error
var successor = self.Successors; ---> This gives error
Error CS1061: 'WorkItemWrapper' does not contain a definition for 'Successor' 

Thanks,
Kamran

**Comment by giuliov** [comment]
There is no `Successor` property. You need to loop though the
`Relations` collection and check the [`Rel`](https://github.com/tfsaggregator/aggregator-cli/blob/master/doc/rule-language.md#workitemrelation-type) property for `System.LinkTypes.Dependency-Forward`, something like

```
foreach (var successor in self.Relations.Where(r=>Rel == "System.LinkTypes.Dependency-Forward")) {
 // do something
}
```
(untested code, may contain syntax or functional mistakes)

Why there is no `Successors` property? Because there are many link types and you can add custom ones, so we expose a helpers just for the Parent/Child relationship, the most common usage.
Check the [Rule Language](https://github.com/tfsaggregator/aggregator-cli/blob/master/doc/rule-language.md) page for what is available.

**Comment by KamranAslamBhatti** [comment]
Thanks giuliov for you prompt reply, I am getting the following error when try to run the code, do I need to import or reference to some namespace to use Rel property.

foreach (var successor in self.Relations.Where(r=>Rel=="System.LinkTypes.Dependency-Forward"))
{
successor["Microsoft.VSTS.Scheduling.StartDate"] =self["Microsoft.VSTS.Scheduling.StartDate"];
}
error CS0103: The name 'Rel' does not exist in the current context

Thanks,
Kamran

**Comment by giuliov** [comment]
Not sure, maybe you need to set the type explicitly or add a namespace.

**Comment by BobSilent** [comment]
This works,

```csharp
var allWorkItemLinks = self.RelationLinks;
foreach(var successorLink in allWorkItemLinks.Where(link => string.Equals("System.LinkTypes.Dependency-Forward", link.Rel)))
{
    // get work item id from link and parse to integer
    var id = int.Parse(successorLink.Url.Split('/').Last());
    // now load the workitem
    var successor = store.GetWorkItem(id);

    successor.Title = "new Title: (predecessor " + self.Title + ")";
}

return self.Title;
```

but I see it is quite complicated, maybe we should improve here

1. I will provide a pull request to update rule examples with this code snippet
2. improve handling of relations to at least provide the linked Id for loading the work item via ```store```

**Comment by KamranAslamBhatti** [comment]
Thanks BobSilent it worked :)
Above provided code resolved the issue, thanks alot :)
