### ISSUE TITLE
Error with retrieve a workitem with attachment

### ISSUE THREAD

**Issue by adu80** [tfsaggregator/aggregator-cli#99]
![image](https://user-images.githubusercontent.com/47635488/72341142-d0f0f480-36c9-11ea-9215-45e737abd00b.png)

Occurs when a workitem have a relation to an attachment.

```csharp
aggregator.Engine.WorkItemRelationWrapper.WorkItemRelationWrapper(string relationUrl)

var id = int.Parse(relationUri.Segments.Last());
LinkedId = new PermanentWorkItemId(id);
```
In this case, the last segment is not an integer but a guid.

I proposed this fix (before to do a wrong pull request >.<) :
```csharp
aggregator.Engine.WorkItemRelationWrapperCollection.WorkItemRelationWrapperCollection(WorkItemWrapper workItem, IList<WorkItemRelation> relations)

_original = relations == null
                        ? new List<WorkItemRelationWrapper>()
                        : relations.Where(relation => 
                                            !relation.Rel.Equals("ArtifactLink") 
                                            && !relation.Rel.Equals("AttachedFile")
                                            && !relation.Rel.Equals("Hyperlink"))
                                   .Select(relation => new WorkItemRelationWrapper(relation))
                                   .ToList();
```

**Comment by BobSilent** [comment]
This looks like a fix.
I am struggling a little bit with it due to #89 and 
also as the `WorkItemRelationWrapperCollection` currently has an `AddHyperlink` Method, which makes this a little bit strange in using: you do not get the already linked hyperlinks, but you could add some.

Nevertheless I am not happy in total with the overall handling in the implementation here today. 
As I started for #88 and also facing some limitations in relation handling.

But, to have a quick fix here i would currently thinking more about something like that
```csharp
aggregator.Engine.WorkItemRelationWrapper.WorkItemRelationWrapper(string relationUrl)

var idName = relationUri.Segments.Last();
var id = int.TryParse(idName, out var i) ? i : (int?)null;
LinkedId = id == null ? null : new PermanentWorkItemId(id.Value);
```

- this would not filter and remove the attachment and hyperlinks from the collection
- would lead to a null ref exception when accessing linkedId for non workitem links
but for me the exception would be currenlty ok, as the linkedId is introduced with latest release and should therefore not have a quite spread usage.

in a next step i will have a deeper look about how #88 and #89 can get together in a simple and easy way
